#!/usr/bin/env sh
set -euo pipefail
IFS=$'\n\t'

echo "Building smjs..."
yarn

for dir in $(ls "projects"); do
    (
        echo "Building ${dir}..."
        cd "./projects/${dir}" && yarn
    )
done
