#!/usr/bin/env sh

echo "Running tests for smjs..."
yarn test tests

for dir in $(ls "projects"); do
    (
        echo "Running tests for ${dir}..."
        cd "./projects/${dir}" && yarn test
    )
done
