#!/usr/bin/env sh
set -euo pipefail
IFS=$'\n\t'

echo "Running tests for smjs..."
yarn test $(pwd)/tests

for dir in $(ls "projects"); do
    (
        echo "Running tests for ${dir}..."
        cd "./projects/${dir}" && yarn test
    )
done
