const Byte = require('../../DataTypes/Byte');

module.exports = {
    al: new Byte(0x00),
    ah: new Byte(0x01),
    ax: new Byte(0x02),
    eax: new Byte(0x03),
    bl: new Byte(0x04),
    bh: new Byte(0x05),
    bx: new Byte(0x06),
    ebx: new Byte(0x07),
    cl: new Byte(0x08),
    ch: new Byte(0x09),
    cx: new Byte(0x0A),
    ecx: new Byte(0x0B),
    dl: new Byte(0x0C),
    dh: new Byte(0x0D),
    dx: new Byte(0x0E),
    edx: new Byte(0x0F),
    mov: new Byte(0x00),
    movi: new Byte(0x01),
    movim: new Byte(0x04),
    movm: new Byte(0x02),
    movrm: new Byte(0x05),
    syscall: new Byte(0x10),
};
