const Byte = require('../../DataTypes/Byte');
const addresses = require('./RegisterAddress').generate(4);

module.exports = {
    register: {
        eax: addresses[0].whole,
        ax: addresses[0].half,
        ah: addresses[0].leftq,
        al: addresses[0].rightq,
        ebx: addresses[1].whole,
        bx: addresses[1].half,
        bh: addresses[1].leftq,
        bl: addresses[1].rightq,
        ecx: addresses[2].whole,
        cx: addresses[2].half,
        ch: addresses[2].leftq,
        cl: addresses[2].rightq,
        edx: addresses[3].whole,
        dx: addresses[3].half,
        dh: addresses[3].leftq,
        dl: addresses[3].rightq,
    },
    instruction: {
        mov: new Byte(0x00),
        movi: new Byte(0x01),
        movim: new Byte(0x02),
        movipb: new Byte(0x03),
        movipw: new Byte(0x04),
        movipd: new Byte(0x05),
        movimp: new Byte(0x06),
        movm: new Byte(0x07),
        movp: new Byte(0x08),
        movrm: new Byte(0x09),
        movrp: new Byte(0x0A),
        movrmp: new Byte(0x0B),
        inc: new Byte(0x10),
        dec: new Byte(0x11),
        addi: new Byte(0x12),
        add: new Byte(0x13),
        addm: new Byte(0x14),
        subi: new Byte(0x15),
        sub: new Byte(0x16),
        subm: new Byte(0x17),
        muli: new Byte(0x18),
        mul: new Byte(0x19),
        mulm: new Byte(0x1A),
        cmp: new Byte(0x20),
        cmpi: new Byte(0x21),
        cmpm: new Byte((0x22)),
        jmp: new Byte(0x30),
        je: new Byte(0x31),
        jne: new Byte(0x32),
        jg: new Byte(0x33),
        jge: new Byte(0x34),
        jl: new Byte(0x35),
        jle: new Byte(0x36),
        syscall: new Byte(0xF0),
    },
};
